### ISSUE TITLE
无法正常获取 X-FORWARDED-FOR / X-REAL-IP 等值

### ISSUE THREAD

**Issue by willove** [fucongcong/GroupCo#11]
在控制器里面需要获取用户IP，直接用 REMOTE_ADDR 不太准确，因为前面加了nginx，可能就会用到  X-FORWARDED-FOR / X-REAL-IP 等值。但是直接$_SERVER[' X-FORWARDED-FOR']出不来数据。

我看了下源码，好像是 symfony2 的 Request组件并没有将swoole拿到的 $request 里 header 解析出来。我在App.php terminate方法里面 调用 new \Request 前把 $request->server $request->header 合并了

`$request->server = array_merge($request->server, array_change_key_case($request->header, CASE_UPPER));`

控制器里输出 $request->server->all() ，临时解决的路子，终于也是可以看到了。。

![image](https://user-images.githubusercontent.com/5616317/34374042-b934e1d8-eb19-11e7-8eb2-b4b75f8b3dfc.png)

可否更新一下这方面的代码。。

**Comment by fucongcong** [comment]
https://github.com/fucongcong/co-framework/pull/21
最新master已增加。你可以$request->headers->all()获取或者$request->getClientIps()。
