### ISSUE TITLE
无法接收content-type 为application/json的数据

### ISSUE THREAD

**Issue by willove** [fucongcong/GroupCo#26]
swoole 文档中对于 非 `application/x-www-form-urlencoded`格式的Http POST请求 可以通过 `swoole_http_request->rawContent` 来获取，但是在框架中并不能直接获取到以 `application/json` 方式 POST过来的数据。希望可以解决这个问题。

**Comment by fucongcong** [comment]
谢谢反馈，最新版本已修复。composer update 更新框架co-framework 2.0.1pre release
获取方式为>> $request->getContent()

**Comment by willove** [comment]
更新版本可以识别出来 application/json 数据了，但是又来了一个问题

`Notice: Undefined index: content-type in XXXX/vendor/group-co/framework/core/Group/App/App.php on line 115`

很明显是 headers 里面并没有 content-type 这个字段。原因在于 HTTP GET 方式的 headers 没有 content-type 字段的，这里就尴尬了，可以改进一下么？

**Comment by fucongcong** [comment]
更新最新版 ，后来我修复了这个warning

**Comment by fucongcong** [comment]
因为版本发布会有一定滞后，你可以将composer.json中的"group-co/framework": "^v2.0.1" 改为 
"group-co/framework": "dev-master"  直接获取最新master的代码
