### ISSUE TITLE
框架问题 

### ISSUE THREAD

**Issue by Skobo** [fucongcong/GroupCo#37]
DefaultController 里面的
yield "===hello world!===";  
这个字符串修改后，只有重启server.php 才生效？是不是，每提交一起代码，就要重启一些server.php

**Comment by fucongcong** [comment]
常驻内存就是这样的 ，与传统php实时编译不同，修改完文件需要重启才能生效。类似java文件修改后你需要重新编译运行才可以

**Comment by Skobo** [comment]
谢谢大佬解答 ，我只会，c 和php，不会java，所以思维还停在以前的php框架上

**Comment by feng99** [comment]
是php-fpm工作机制导致业务代码不能常驻内存。
